import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const font = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}

// i need a hero section
// currently building - boltapply - create a cover letter in less than 15 seconds. currently in beta. to be released Q3 2024.
// portfolio section - scrolls to below - done
// reviews section - done
// boltapply
// clinitOS
// ratingUp
// websites and shits
